# Exercício de Programação 1

<font color="red">**Prazo de submissão: 23:55 do dia 19/03/2020** </font>

2020.1 Álgebra Linear Computacional - DCC - UFMG

Erickson - Fabricio

Instruções:
* Antes de submeter suas soluções, certifique-se de que tudo roda como esperado. Primeiro, **reinicie o kernel** no menu, selecione Kernel$\rightarrow$Restart e então execute **todas as células** (no menu, Cell$\rightarrow$Run All)
* Apenas o arquivo .ipynb deve ser submetido. Ele não deve ser compactado.
* Não deixe de preencher seu nome e número de matrícula na célula a seguir

Nome do aluno: Victor Moura Martins da Costa

Matricula: 2017014766

## Parte 1: Python básico

In [1]:
# Exercício 1 - Imprima na tela os números de 1 a 10 e armazene-os em uma lista.
lista = []
for x in range(1,11):
    print(x)
    lista += [x]

1
2
3
4
5
6
7
8
9
10


In [2]:
# Exercício 2 - Crie duas strings e concatene as duas em uma terceira string
string1 = 'Hello'
string2 = 'World'
string3 = string1 + ' ' + string2
print(string3)

Hello World


In [3]:
# Exercício 3 - Crie uma tupla com os seguintes elementos: 1, 2, 2, 3, 4, 4, 4, 5 e depois utilize a função count do 
# objeto tupla para verificar quantas vezes o número 4 aparece na tupla
tupla = (1, 2, 2, 3, 4, 4, 4, 5)
x = tupla.count(4)
print(x)

3


In [4]:
# Exercício 4 - Crie um dicionário com 3 chaves e 3 valores e imprima na tela
dicionario = {"nome":"Victor", "sobrenome":"Moura", "idade":21}
print(dicionario)

{'nome': 'Victor', 'sobrenome': 'Moura', 'idade': 21}


In [5]:
# Exercício 5 - Adicione mais um elemento ao dicionário criado no exercício anterior e imprima na tela
dicionario["matricula"] = 2017014766
print(dicionario)

{'nome': 'Victor', 'sobrenome': 'Moura', 'idade': 21, 'matricula': 2017014766}


In [6]:
# Exercício 6 - Crie um novo dicionário invertendo o anterior (isto é, usando os valores como chave e vice-versa)
dicionarioInvertido = {"Victor":"nome", "Moura":"sobrenome", "21":"idade", "2017014766": "matricula"}
print(dicionarioInvertido)

{'Victor': 'nome', 'Moura': 'sobrenome', '21': 'idade', '2017014766': 'matricula'}


In [7]:
# Exercício 7 - Crie uma função que receba uma string como argumento e retorne a mesma string em letras maiúsculas.
# Faça uma chamada à função, passando como parâmetro uma string
def transforma_maiuscula(string):
    string_maiuscula = string.upper()
    return string_maiuscula

string = "Hello World"
transforma_maiuscula(string)

'HELLO WORLD'

In [8]:
# Exercício 8 - Crie uma função que receba como parâmetro uma lista de 4 elementos, adicione 2 elementos a lista e 
# imprima a lista. Esta função não deve retornar nada.
def recebe_lista(lista):
    lista.append(5)
    lista.append(6)

lista = [1, 2, 3, 4]
recebe_lista(lista)
print(lista)

[1, 2, 3, 4, 5, 6]


In [9]:
# Exercício 9 - Faça a correção dos erros no código abaixo e execute o programa. Dica: são 3 erros.
temperatura = float(input('Qual a temperatura? '))
if temperatura > 30:
    print('Vista roupas leves.')
else:
    print('Busque seus casacos.')

Qual a temperatura? 30
Busque seus casacos.


In [10]:
# Exercício 10 - Crie uma função que conte quantas vezes a letra "r" aparece na frase abaixo. Use um placeholder (%) na 
# sua instrução de impressão
frase = "All models are wrong, but some are useful (George Box)"
def conta_r(string):
    return string.count("r")

contador = conta_r(frase)
print('%d' % (contador))

4


## Parte 2: numpy

## Questão 1

Crie as matrizes A, B e C abaixo e resolva as questões:
1. [ ] Calcule $(((A^T B)+B)C^{-1})$
2. [ ] Crie matrizes $\tilde A_{2x2}, \tilde B_{2x2}, \tilde C_{2x2}$, tal que sejam compostas pelo 2 primeiros elementos de cada linha das duas primeiras linhas. E repita a equação do item anterior.

**Dica** numpy.full, numpy.eye, numpy.ones e indexação de vetores.

$$
A = \begin{bmatrix}
 8 & 8 & 8\\
 8 & 8 & 8\\
 8 & 8 & 8
\end{bmatrix}_{3\times 3}
\qquad
B = \begin{bmatrix}
 1 & 1 & 1 & 1\\
 1 & 1 & 1 & 1\\
 1 & 1 & 1 & 1
\end{bmatrix}_{3\times 4}
\qquad
C = \begin{bmatrix}
 1 & 0 & 0 & 0 \\
 0 & 1 & 0 & 0 \\
 0 & 0 & 1 & 0 \\
 0 & 0 & 0 & 1
\end{bmatrix}_{4\times 4}
$$

In [11]:
import numpy as np

# Equação dos 2 exercícios
def equacao(A, B, C):
    A_transposta = A.transpose()
    C_inversa = np.linalg.inv(C)
    AxB = A_transposta.dot(B)

    A_B = np.add(AxB, B)
    resultado = A_B.dot(C_inversa)
    return resultado

# Código para Exercício 1
A1 = np.array([[8,8,8],[8,8,8],[8,8,8]])
B1 = np.array([[1,1,1,1],[1,1,1,1],[1,1,1,1]])
C1 = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

q1 = equacao(A1, B1, C1)
print('Exercício 1:\n', q1)

# Código para Exercício 2
A2 = np.array([[8,8],[8,8]])
B2 = np.array([[1,1],[1,1]])
C2 = np.array([[1,0],[0,1]])

q2 = equacao(A2, B2, C2)
print('\nExercício 2:\n', q2)

Exercício 1:
 [[25. 25. 25. 25.]
 [25. 25. 25. 25.]
 [25. 25. 25. 25.]]

Exercício 2:
 [[17. 17.]
 [17. 17.]]


## Questão 2
**2A.** Escreva uma função python que recebe $m$ como entrada e executa os seguintes passos:
1. [ ] gera uma matriz aleatória $W_{m \times 4}$ (função **numpy.random.randn**),
2. [ ] divide cada uma das entradas por $\sqrt{m}$ (salva resultado em $\tilde W$),
3. [ ] calcula $Z = \tilde W^\top \times \tilde W$,
4. [ ] imprime $Z$,
5. [ ] calcula a norma Frobenius da diferença entre $Z$ e a matriz identidade $I_{4 \times 4}$.

In [12]:
# Código para Exercício 2
def Frobenius(m):
    W = np.random.randn(m, 4)
    W2 = W / np.sqrt(m)
    Z = (W2.transpose()).dot(W2)
    print(Z)
    
    # Frobenius
    I = np.array([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
    sub = np.subtract(Z, I)
    return np.linalg.norm(sub, 'fro')

**2B.** Qual a norma da diferença obtida para $m=100$? E para $m=10000$?

Resposta:

In [13]:
print('m = 100')
print(Frobenius(100))
print('\nm = 1000')
print(Frobenius(1000))

m = 100
[[ 1.20598516  0.10445493 -0.15978146  0.13114251]
 [ 0.10445493  0.99122633  0.25647036 -0.15381151]
 [-0.15978146  0.25647036  1.18740086  0.16335364]
 [ 0.13114251 -0.15381151  0.16335364  1.34106165]]
0.7303878955710206

m = 1000
[[ 0.97643119  0.0651096  -0.06486148  0.05103092]
 [ 0.0651096   0.99687947  0.02599664 -0.07003536]
 [-0.06486148  0.02599664  0.96942026 -0.0470107 ]
 [ 0.05103092 -0.07003536 -0.0470107   0.96844035]]
0.2004464402801794


**2C.** O que podemos dizer sobre a matriz $\tilde W$?

Resposta: 
Enquanto a matriz $W$ pode ser uma projeção qualquer em um subespaço, a matriz $\tilde W$ poderá corresponder a projeção de um complemento ortogonal do subespaço de $W$.